debug: false
spring:
  datasource:
    url: jdbc:mysql://localhost/budgetapp?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: toor
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true